apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome
  template:
    metadata:
      labels:
        app: selenium-chrome
    spec:
      containers:
      - name: selenium-chrome
        image: selenium/standalone-chrome:latest
        ports:
        - containerPort: 4444
        - containerPort: 7900

---

apiVersion: v1
kind: Service
metadata:
  name: selenium-service
spec:
  selector:
    app: selenium-chrome
  ports:
    - name: backend
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: frontend
      protocol: TCP
      port: 7900
      targetPort: 7900
  type: LoadBalancer