global:
  K8S_PUBLIC_IP: "10.10.10.10"
  seleniumGrid:
    logLevel: INFO

tls:
  enabled: false

ingress:
  enabled: false

basicAuth:
  enabled: false

isolateComponents: true

chromeNode:
  scaledOptions:
    minReplicaCount: 1
    maxReplicaCount: 16
    pollingInterval: 10

firefoxNode:
  enabled: false

edgeNode:
  enabled: false

videoRecorder:
  enabled: false

ingress-nginx:
  enabled: true